<template>
  <div class="row">
    <div class="offset-md-3 col-md-6 col-sm-12">
      <h2>Privacy Policy</h2>

      <p>Effective date: 2023-07-27</p>

      <h4>Introduction</h4>

      <p>Welcome to CodeRev.app (“Company”, “we”, “our”, “us”)!</p>

      <p>
        These Terms of Service (“Terms”, “Terms of Service”) govern your use of
        our web pages located at https://coderev.app operated by Charles Chen.
      </p>

      <p>
        Our Privacy Policy also governs your use of our Service and explains how
        we collect, safeguard and disclose information that results from your
        use of our web pages. Please read it here https://coderev.app/privacy.
      </p>

      <p>
        Your agreement with us includes these Terms and our Privacy Policy
        (“Agreements”). You acknowledge that you have read and understood
        Agreements, and agree to be bound of them.
      </p>

      <p>
        If you do not agree with (or cannot comply with) Agreements, then you
        may not use the Service, but please let us know by emailing at
        chen.charles.c@gmail.com so we can try to find a solution. These Terms
        apply to all visitors, users and others who wish to access or use
        Service.
      </p>

      <p>Thank you for being responsible.</p>

      <h4>Definitions</h4>

      <p>
        SERVICE means the https://coderev.app website operated by CodeRev.app.
      </p>

      <p>
        PERSONAL DATA means data about a living individual who can be identified
        from those data (or from those and other information either in our
        possession or likely to come into our possession).
      </p>

      <p>
        USAGE DATA is data collected automatically either generated by the use
        of Service or from Service infrastructure itself (for example, the
        duration of a page visit).
      </p>

      <p>
        COOKIES are small files stored on your device (computer or mobile
        device).
      </p>

      <p>
        DATA CONTROLLER means a natural or legal person who (either alone or
        jointly or in common with other persons) determines the purposes for
        which and the manner in which any personal data are, or are to be,
        processed. For the purpose of this Privacy Policy, we are a Data
        Controller of your data.
      </p>

      <p>
        DATA PROCESSORS (OR SERVICE PROVIDERS) means any natural or legal person
        who processes the data on behalf of the Data Controller. We may use the
        services of various Service Providers in order to process your data more
        effectively.
      </p>

      <p>
        DATA SUBJECT is any living individual who is the subject of Personal
        Data.
      </p>

      <p>
        THE USER is the individual using our Service. The User corresponds to
        the Data Subject, who is the subject of Personal Data.
      </p>

      <h4>Information Collection and Use</h4>

      <p>
        We collect several different types of information for various purposes
        to provide and improve our Service to you.
      </p>

      <h4>Definitions</h4>

      <p><strong>Personal Data</strong></p>
      <p>
        While using our Service, we may ask you to provide us with certain
        personally identifiable information that can be used to contact or
        identify you (“Personal Data”). Personally identifiable information may
        include, but is not limited to:
      </p>

      <p><strong>Cookies and Usage Data</strong></p>
      <p>
        We may use your Personal Data to contact you with newsletters, marketing
        or promotional materials and other information that may be of interest
        to you. You may opt out of receiving any, or all, of these
        communications from us by following the unsubscribe link or by emailing
        at chen.charles.c@gmail.com.
      </p>

      <p><strong>Usage Data</strong></p>
      <p>
        We may also collect information that your browser sends whenever you
        visit our Service or when you access Service by or through a mobile
        device (“Usage Data”).
      </p>

      <p>
        This Usage Data may include information such as your computer's Internet
        Protocol address (e.g. IP address), browser type, browser version, the
        pages of our Service that you visit, the time and date of your visit,
        the time spent on those pages, unique device identifiers and other
        diagnostic data.
      </p>

      <p>
        When you access Service with a mobile device, this Usage Data may
        include information such as the type of mobile device you use, your
        mobile device unique ID, the IP address of your mobile device, your
        mobile operating system, the type of mobile Internet browser you use,
        unique device identifiers and other diagnostic data.
      </p>

      <p><strong>Tracking Cookies Data</strong></p>
      <p>
        We use cookies and similar tracking technologies to track the activity
        on our Service and we hold certain information.
      </p>

      <p>
        Cookies are files with a small amount of data which may include an
        anonymous unique identifier. Cookies are sent to your browser from a
        website and stored on your device. Other tracking technologies are also
        used such as beacons, tags and scripts to collect and track information
        and to improve and analyze our Service.
      </p>

      <p>
        You can instruct your browser to refuse all cookies or to indicate when
        a cookie is being sent. However, if you do not accept cookies, you may
        not be able to use some portions of our Service.
      </p>

      <p>Examples of Cookies we use:</p>
      <ul>
        <li>Session Cookies: We use Session Cookies to operate our Service.</li>
        <li>
          Preference Cookies: We use Preference Cookies to remember your
          preferences and various settings.
        </li>
        <li>
          Security Cookies: We use Security Cookies for security purposes.
        </li>
        <li>
          Advertising Cookies: Advertising Cookies are used to serve you with
          advertisements that may be relevant to you and your interests.
        </li>
      </ul>

      <h4>Use of Data</h4>

      <p>We use the collected data for various purposes:</p>
      <ul>
        <li>to provide and maintain our Service;</li>
        <li>to notify you about changes to our Service;</li>
        <li>
          to allow you to participate in interactive features of our Service
          when you choose to do so;
        </li>
        <li>to provide customer support;</li>
        <li>
          to gather analysis or valuable information so that we can improve our
          Service;
        </li>
        <li>to monitor the usage of our Service;</li>
        <li>to detect, prevent and address technical issues;</li>
        <li>to fulfill any other purpose for which you provide it;</li>
        <li>
          to carry out our obligations and enforce our rights arising from any
          contracts entered into between you and us, including for billing and
          collection;
        </li>
        <li>
          to provide you with notices about your account and/or subscription,
          including expiration and renewal notices, email-instructions, etc.;
        </li>
        <li>
          to provide you with news, special offers and general information about
          other goods, services and events which we offer that are similar to
          those that you have already purchased or enquired about unless you
          have opted not to receive such information;
        </li>
        <li>
          in any other way we may describe when you provide the information;
        </li>
        <li>for any other purpose with your consent.</li>
      </ul>

      <h4>Retention of Data</h4>

      <p>
        We will retain your Personal Data only for as long as is necessary for
        the purposes set out in this Privacy Policy. We will retain and use your
        Personal Data to the extent necessary to comply with our legal
        obligations (for example, if we are required to retain your data to
        comply with applicable laws), resolve disputes, and enforce our legal
        agreements and policies.
      </p>

      <p>
        We will also retain Usage Data for internal analysis purposes. Usage
        Data is generally retained for a shorter period, except when this data
        is used to strengthen the security or to improve the functionality of
        our Service, or we are legally obligated to retain this data for longer
        time periods.
      </p>

      <h4>Transfer of Data</h4>

      <p>
        Your information, including Personal Data, may be transferred to – and
        maintained on – computers located outside of your state, province,
        country or other governmental jurisdiction where the data protection
        laws may differ from those of your jurisdiction.
      </p>

      <p>
        If you are located outside United States and choose to provide
        information to us, please note that we transfer the data, including
        Personal Data, to United States and process it there.
      </p>

      <p>
        Your consent to this Privacy Policy followed by your submission of such
        information represents your agreement to that transfer.
      </p>

      <p>
        CodeRev.app will take all the steps reasonably necessary to ensure that
        your data is treated securely and in accordance with this Privacy Policy
        and no transfer of your Personal Data will take place to an organization
        or a country unless there are adequate controls in place including the
        security of your data and other personal information.
      </p>

      <h4>Disclosure of Data</h4>

      <p>
        We may disclose personal information that we collect, or you provide:
      </p>

      <p><strong>Disclosure for Law Enforcement.</strong></p>
      <p>
        Under certain circumstances, we may be required to disclose your
        Personal Data if required to do so by law or in response to valid
        requests by public authorities.
      </p>

      <p><strong>Business Transaction.</strong></p>
      <p>
        If we or our subsidiaries are involved in a merger, acquisition or asset
        sale, your Personal Data may be transferred.
      </p>

      <p>Other cases. We may disclose your information also:</p>

      <ul>
        <li>to our subsidiaries and affiliates;</li>
        <li>
          to contractors, service providers, and other third parties we use to
          support our business;
        </li>
        <li>to fulfill the purpose for which you provide it;</li>
        <li>
          for the purpose of including your company’s logo on our website;
        </li>
        <li>
          for any other purpose disclosed by us when you provide the
          information;
        </li>
        <li>with your consent in any other cases;</li>
        <li>
          if we believe disclosure is necessary or appropriate to protect the
          rights, property, or safety of the Company, our customers, or others.
        </li>
      </ul>

      <h4>Security of Data</h4>

      <p>
        The security of your data is important to us but remember that no method
        of transmission over the Internet or method of electronic storage is
        100% secure. While we strive to use commercially acceptable means to
        protect your Personal Data, we cannot guarantee its absolute security.
      </p>

      <h4>Links to Other Sites</h4>

      <p>
        Our Service may contain links to other sites that are not operated by
        us. If you click a third party link, you will be directed to that third
        party's site. We strongly advise you to review the Privacy Policy of
        every site you visit.
      </p>

      <p>
        We have no control over and assume no responsibility for the content,
        privacy policies or practices of any third party sites or services.
      </p>

      <h4>Changes to this Privacy Policy</h4>

      <p>
        We may update our Privacy Policy from time to time. We will notify you
        of any changes by posting the new Privacy Policy on this page.
      </p>

      <p>
        We will let you know via email and/or a prominent notice on our Service,
        prior to the change becoming effective and update “effective date” at
        the top of this Privacy Policy.
      </p>

      <p>
        You are advised to review this Privacy Policy periodically for any
        changes. Changes to this Privacy Policy are effective when they are
        posted on this page.
      </p>
    </div>
  </div>
</template>

<script setup lang="ts">
definePageMeta({
  layout: "empty",
});
</script>

<style scoped>
body * {
  background-color: #fff;
  color: #000 !important;
}
</style>
